SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent: ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
        
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System.Linq;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IStoreRepository repository;
        public NavigationMenuViewComponent(IStoreRepository repository)
        {
            this.repository = repository;
        }
        public IViewComponentResult Invoke()
        {   var routeData= RouteData?.Values["category"];
            ViewBag.SelectedCategory = routeData;
            return View(repository.Products
            .Select(x=>x.Category)
            .Distinct()
            .OrderBy(x=>x));
        }
        
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span style="float:right" class="badge badge-pill badge-primary">
                    <small>@Model.Price.ToString("C")</small>
            </span>
        </h4>
    </div>
  <form id="@Model.ProductID" asp-page="/Cart" method="POST">
    <input type="hidden" asp-for="ProductID">
    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
    <span class="card-text p-1">
        @Model.Description
    </span>
    <button type="submit"
    class="btn btn-success btn-default
    btn-sm btn-pull-right" style="float:right">
         AddToCart
    </button>
 </form>
</div>
 

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<head>
    <meta name="viewport" content="width=device-width">
    <title>SportStore</title>
    <link rel="stylesheet" href="/lib/twitter-bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/lib/font-awesome/css/all.min.css">
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
              <div class="col navbar-brand">SPORTS STORE</div>
              <div class="col-6 text-right">
                    <vc:cart-summary/>
                </div>
             </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
          <vc:navigation-menu />
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
  
</body>


</html>